# Generated by Django 4.1 on 2022-08-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressuserprofile',
            name='number_adress',
            field=models.IntegerField(null=True, verbose_name='numero de calle'),
        ),
        migrations.AlterField(
            model_name='addressuserprofile',
            name='postal_code',
            field=models.IntegerField(null=True, verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='addressuserprofile',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='domicilio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number_adress',
            field=models.IntegerField(null=True, verbose_name='numero de domicilio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number_phone',
            field=models.IntegerField(null=True, verbose_name='numero de telefono'),
        ),
    ]
