# Generated by Django 4.1 on 2023-01-05 11:41

import django.contrib.auth.models
from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('object', user.models.UserProfileManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
